version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-layer-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jx3h3o6mj7ty"
s3_prefix = "lambda-layer-sam"
region = "ap-southeast-1"
profile = "default"
capabilities = "CAPABILITY_IAM"
